{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/connectError"},"abstract":[{"type":"text","text":"The connection established in response to a "},{"code":"CONNECT","type":"codeVoice"},{"type":"text","text":" request"},{"type":"text","text":" "},{"type":"text","text":"was reset or abnormally closed."}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["Linux"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","kind":"typeIdentifier","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niohttp2\/http2errorcode\/connecterror"]}],"metadata":{"symbolKind":"property","modules":[{"name":"NIOHTTP2"}],"roleHeading":"Type Property","externalID":"s:8NIOHTTP214HTTP2ErrorCodeV07connectC0ACvpZ","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","kind":"typeIdentifier"}],"title":"connectError"},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTP2ErrorCode"}],"abstract":[{"type":"text","text":"An HTTP\/2 error code."}],"type":"topic","url":"\/documentation\/niohttp2\/http2errorcode","title":"HTTP2ErrorCode","navigatorTitle":[{"kind":"identifier","text":"HTTP2ErrorCode"}]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode/connectError":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/connectError","abstract":[{"type":"text","text":"The connection established in response to a "},{"code":"CONNECT","type":"codeVoice"},{"type":"text","text":" request"},{"type":"text","text":" "},{"type":"text","text":"was reset or abnormally closed."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","text":"HTTP2ErrorCode"}],"title":"connectError","url":"\/documentation\/niohttp2\/http2errorcode\/connecterror"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"title":"NIOHTTP2","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/niohttp2"}}}